# Generated by Django 5.1 on 2024-08-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=255)),
                ('client_address', models.CharField(max_length=255)),
                ('price_sell', models.FloatField()),
                ('commande_state', models.CharField(default='En_attente', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
