# Generated by Django 5.1 on 2024-08-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='commande_state',
        ),
        migrations.AddField(
            model_name='commande',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='price_sell',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
