# Generated by Django 5.1 on 2024-09-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_commande_loss_commande_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
