# Generated by Django 5.1 on 2024-09-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_alter_commande_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.CharField(max_length=234),
        ),
    ]
