# Generated by Django 5.1 on 2024-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0011_alter_commande_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='loss',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.CharField(max_length=234),
        ),
    ]
