# Generated by Django 5.1 on 2024-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='none', max_length=255)),
                ('relation', models.CharField(default='partner', max_length=255)),
                ('is_contract', models.BooleanField(default=True)),
                ('contract_begin', models.DateField(auto_now=True)),
                ('contract_end', models.DateField(blank=True)),
                ('num_tel', models.CharField(max_length=200)),
                ('num_fax', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('webSite', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
