# Generated by Django 5.1 on 2024-09-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseau',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partnerslogo/'),
        ),
    ]
