# Generated by Django 5.1 on 2024-09-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profitaire', models.CharField(max_length=255)),
                ('valeur', models.FloatField()),
                ('type', models.CharField(max_length=255)),
                ('is_Money', models.BooleanField(default=True)),
                ('is_Products', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('ToPayBefore', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
