# Generated by Django 5.1 on 2024-09-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='ToPayBefore',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='is_Products',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='type',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='valeur',
        ),
        migrations.AddField(
            model_name='credit',
            name='comments',
            field=models.CharField(default='None', max_length=2500),
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_payer',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_value',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='credit',
            name='hePaysForUs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='otherSideAdress',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='credit',
            name='otherSideEmail',
            field=models.EmailField(default='None@none.com', max_length=254),
        ),
        migrations.AddField(
            model_name='credit',
            name='otherSidePhone',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='credit',
            name='profitaire',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='credit',
            name='toPayBefore',
            field=models.DateField(null=True),
        ),
    ]
