# Generated by Django 5.1 on 2024-08-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=255)),
                ('price_buy', models.FloatField()),
                ('price_sell', models.FloatField()),
                ('price_sell_if_promo', models.FloatField()),
                ('product_description', models.CharField(max_length=5000)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_image4', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_image5', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
    ]
