# Generated by Django 5.1 on 2024-08-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_sell_if_promo',
            field=models.FloatField(blank=True),
        ),
    ]
