# Generated by Django 5.1 on 2024-08-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price_sell_if_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_sell_if_promo',
        ),
    ]
